all: ZombieDash

LIBS=-lzdk -lncurses -lm -lrt
DIRS=-I../ZDK -L../ZDK
FLAGS=-std=gnu99 -D_XOPEN_SOURCE=500 -Wall -Werror

clean:
	rm ZombieDash

rebuild: clean all

SRC=main.c game.c player.c zombie.c
HDR=game.h player.h zombie.h

ZombieDash: $(SRC) $(HDR)
	gcc $(FLAGS) $(SRC) -o $@ $(DIRS) $(LIBS) 
